name: Daily Email Sender

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 09:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  send_email:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
      BIBLE_API_KEY: ${{ secrets.BIBLE_API_KEY }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
